name: bay
version: 0.0.1
author: Diego Rocha <diego.rocha.comp@gmail.com>
description: An easy HTTP service builder with dependency injection supported by Dado. Definitely an awesome way to structure your backend.
homepage: https://github.com/Dreckr/Bay
environment:
  sdk: '>=1.0.0'
dependencies:
  dado:
    path: ../dado
  http_server: any
  logging: any
  model_map:
    path: ../model_map
  uri: any
dev_dependencies:
  unittest: '>=0.5.0'
